logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  application:
    name: publisher
  rabbitmq:
    host: 192.168.211.132
    port: 5672
    virtual-host: /
    username: itcast
    password: 123321